Modules now link statically, too and Filters seem to handle programs consisting of more than one block correctly.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3148,7 +3148,7 @@ EOF
  
 else
   echo "$ac_t""no" 1>&6
-echo "configure: warning: "Cannot find pisock library support for PalmOS disabled."" 1>&2
+echo "configure: warning: "Cannot find pisock library headers - support for PalmOS disabled."" 1>&2
 fi
 done
 
