configure to match configure.in

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -563,7 +563,7 @@ else
 fi
 
 
-# From configure.in Id: configure.in,v 1.188 2000/09/16 07:25:16 gregnoel Exp 
+# From configure.in Id: configure.in,v 1.189 2000/09/27 23:49:23 gregnoel Exp 
 
 rm -f conftestdata
 if ln -s X conftestdata 2>/dev/null
@@ -4412,10 +4412,12 @@ esac
 DOCHTML="\$(SCANDOCHTML)"
 
 
+
+MAKE_HAVE_DOCTOOLS='HAVE_DOCTOOLS=yes'
 # Extract the first word of "perl", so it can be a program name with args.
 set dummy perl; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:4419: checking for $ac_word" >&5
+echo "configure:4421: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PERL'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -4446,11 +4448,12 @@ if test -n "$PERL"; then
 else
   echo "$ac_t""no" 1>&6
 fi
+case "$PERL" in '') MAKE_HAVE_DOCTOOLS='' PERL='false "No perl available"' ;; esac
 
 # Extract the first word of "latex", so it can be a program name with args.
 set dummy latex; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:4454: checking for $ac_word" >&5
+echo "configure:4457: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_LATEX'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -4481,11 +4484,12 @@ if test -n "$LATEX"; then
 else
   echo "$ac_t""no" 1>&6
 fi
+case "$LATEX" in '') MAKE_HAVE_DOCTOOLS='' LATEX='false "No latex available"' ;; esac
 
 # Extract the first word of "makeindex", so it can be a program name with args.
 set dummy makeindex; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:4489: checking for $ac_word" >&5
+echo "configure:4493: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_MAKEINDEX'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -4516,11 +4520,12 @@ if test -n "$MAKEINDEX"; then
 else
   echo "$ac_t""no" 1>&6
 fi
+case "$MAKEINDEX" in '') MAKE_HAVE_DOCTOOLS='' MAKEINDEX='false "No makeindex available"' ;; esac
 
 # Extract the first word of "dvips", so it can be a program name with args.
 set dummy dvips; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:4524: checking for $ac_word" >&5
+echo "configure:4529: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_DVIPS'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -4551,21 +4556,12 @@ if test -n "$DVIPS"; then
 else
   echo "$ac_t""no" 1>&6
 fi
-
-if test "x$LATEX" = x -o "x$DVIPS" = x -o "x$MAKEINDEX" = x
-then
-	LATEX="echo \"No latex available.\""
-	DVIPS="echo \"No dvips available.\""
-	MAKEINDEX="echo \"No makeindex available.\""
-fi
-
-
-
+case "$DVIPS" in '') MAKE_HAVE_DOCTOOLS='' DVIPS='false "No dvips available"' ;; esac
 
 # Extract the first word of "ps2pdf", so it can be a program name with args.
 set dummy ps2pdf; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:4569: checking for $ac_word" >&5
+echo "configure:4565: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PSTOPDF'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -4596,16 +4592,12 @@ if test -n "$PSTOPDF"; then
 else
   echo "$ac_t""no" 1>&6
 fi
-
-case "$PSTOPDF" in '')
-	PSTOPDF="echo \"ps2pdf not available.\""
-esac
-
+case "$PSTOPDF" in '') MAKE_HAVE_DOCTOOLS='' PSTOPDF='false "No ps2pdf available"' ;; esac
 
 # Extract the first word of "latex2html", so it can be a program name with args.
 set dummy latex2html; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:4609: checking for $ac_word" >&5
+echo "configure:4601: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_LATEX2HTML'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -4636,13 +4628,13 @@ if test -n "$LATEX2HTML"; then
 else
   echo "$ac_t""no" 1>&6
 fi
+case "$LATEX2HTML" in '') MAKE_HAVE_DOCTOOLS='' LATEX2HTML='false "No latex2html available"' ;; esac
 
-case "$LATEX2HTML" in
-'')	LATEX2HTML="echo \"No doc generator(html) available.\""
-	MAKE_HAVE_LATEX2HTML='' ;;
-*)	MAKE_HAVE_SGMLTOOLS="HAVE_LATEX2HTML=yes" ;;
+case "$MAKE_HAVE_DOCTOOLS" in '')
+echo "configure: warning: One of the tools required to build documentation
+is missing.  Documentation cannot be built on this system and you will need
+a pre-built Mdocs.tar.gz instead." 1>&2 ;;
 esac
-
 
 
 
@@ -4892,7 +4884,7 @@ s%@MAKEINDEX@%$MAKEINDEX%g
 s%@DVIPS@%$DVIPS%g
 s%@PSTOPDF@%$PSTOPDF%g
 s%@LATEX2HTML@%$LATEX2HTML%g
-s%@MAKE_HAVE_LATEX2HTML@%$MAKE_HAVE_LATEX2HTML%g
+s%@MAKE_HAVE_DOCTOOLS@%$MAKE_HAVE_DOCTOOLS%g
 s%@CXXFLAGS_RELAXED@%$CXXFLAGS_RELAXED%g
 s%@LIBS_STATIC@%$LIBS_STATIC%g
 
